/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{ts,tsx}', './src/**/*.{ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        appBg: '#F9C56D',
        appBgElevated: '#FAFAFA',
        appCard: '#FFFFFF',
        appCardAlt: '#E3E3E3',
        appBorder: '#BDBDBD',
        appText: '#212121',
        appMuted: '#757575',
        appTextInverse: '#FFFFFF',
        appAccent: '#F9C56D',
        appAccentSoft: '#FBE1A7',
        appDanger: '#D33A2C',
        appWarning: '#F9C56D',
        appWarningBg: '#FFF5DD',
        appWarningBorder: '#F4D28B',
        appOverlay: 'rgba(33, 33, 33, 0.45)',
        appNav: '#212121',
        appNavInactive: '#BDBDBD',
        appNavActive: 'rgba(255, 255, 255, 0.10)',
        appRecordRing: '#FAFAFA',
        appRecordLiveRing: '#FFE082',
        appRecordCore: '#D33A2C',
        appRecordAssistRing: '#FAFAFA',
        appRecordAssistLiveRing: '#FFE082',
        appRecordAssistCore: '#D33A2C',
        appMediaOverlay: 'rgba(33, 33, 33, 0.24)',
      },
      borderRadius: {
        appSm: '10px',
        appMd: '16px',
        appLg: '24px',
        appPill: '999px',
      },
      boxShadow: {
        app: '0 8px 16px rgba(33, 33, 33, 0.12)',
      },
    },
  },
  plugins: [],
};
